apiVersion: batch/v1
kind: Job
metadata:
  name: users-service-migrations
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alembic
          image: e1name/forotus:users-crud
          imagePullPolicy: IfNotPresent
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: users-service-config
            - secretRef:
                name: users-service-secret
