apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
type: Opaque
stringData:
  POSTGRES_USER: users_service_user
  POSTGRES_PASSWORD: users_service_password
  DATABASE_URL: postgresql+asyncpg://users_service_user:users_service_password@users-db-postgresql:5432/users_service
  JWT_SECRET_KEY: super-secret-key
