services:
  migrate:
    build: .
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --app-dir src
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-users_service}
      POSTGRES_USER: ${POSTGRES_USER:-users_service_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-users_service_password}
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-users_service_user} -d ${POSTGRES_DB:-users_service}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
